export const OBTENER_TIPOSOLICITUD_CARGANDO = 'OBTENER_TIPOSOLICITUD_CARGANDO'
export const OBTENER_TIPOSOLICITUD_EXITO = 'OBTENER_TIPOSOLICITUD_EXITO'
export const OBTENER_TIPOSOLICITUD_ERROR = 'OBTENER_TIPOSOLICITUD_ERROR'

