export const modulo = {
   PERFIL: 'PERFIL',
   ACTIVIDADES: 'REGISTRO ACTIVIDADES',
   LINEAMIENTOS: 'LINEAMIENTOS',
   PROCESOS: 'PROCESOS',
   UTILIDADES: 'UTILIDADES',
   REPORTES: 'REPORTES',
}

export const subModulo = {
   REGISTRAR_PRODUCCION             : 'REGISTRAR PRODUCCION',
   NUEVO_INTERPOL                   : 'NUEVO INTERPOL',
   NUEVO_OPERATIVO                  : 'NUEVO OPERATIVO',
   BUSCAR_INTERPOL                  : 'BUSCAR INTERPOL',
   BUSCAR_OPERATIVO                 : 'BUSCAR OPERATIVO',
   REPORTE_SOLICITUDES_MESA_DIGITAL : 'SOLICITUDES MESA DIGITAL',
   REPORTE_OPERATIVOS               : 'OPERATIVOS',
   REPORTE_PRODUCCION               : 'PRODUCCIÓN SUB DIRECCIÓN DE FISCALIZACIÓN MIGRATORIA'
}
