export const modulo = {
   HOME           : 'HOME',
   PERFIL         : 'PERFIL',
   ACTIVIDADES    : 'ACTIVIDADES',
   LINEAMIENTOS   : 'LINEAMIENTOS',
   PROCESOS       : 'PROCESOS',
   UTILIDADES     : 'UTILIDADES',
   REPORTES       : 'REPORTES',
}

export const subModulo = {
   REGISTRAR_PRODUCCION       : 'REGISTRAR PRODUCCIÓN',
   NUEVA_ACTIVIDAD            : 'NUEVA ACTIVIDAD',
   NUEVO_INTERPOL             : 'NUEVO INTERPOL',
   NUEVO_OPERATIVO            : 'NUEVO OPERATIVO',
   BUSCAR_INTERPOL            : 'BUSCAR INTERPOL',
   BUSCAR_OPERATIVO           : 'BUSCAR OPERATIVO',
   BUSCAR_PRE_INSCRIPCION     : 'BUSCAR PREINSCRIPCIÓN',
   BUSCAR_REFUGIADO           : 'BUSCAR REFUGIADO',
   REPORTE_MESA_DIGITAL       : 'REPORTE MESA DIGITAL',
   REPORTE_OPERATIVOS         : 'REPORTE OPERATIVOS',
   REPORTE_PRODUCCION         : 'REPORTE PRODUCCION',
   REPORTE_NACIONALIZACION    : 'REPORTE NACIONALIZACIÓN',
}

export const item = {
   INCONSISTENCIAS   : 'INCONSISTENCIAS',
   PENDIENTES        : 'PENDIENTES',
   NACIONALIZADOS    : 'NACIONALIZADOS',
   ATENDIDOS         : 'ATENDIDOS',
}