import {uuid} from 'short-uuid'
export const produccionDb = {
   descripcionActividadDb:[
      { id: uuid(), descripcion: 'Elaboración de informes técnicos de expedientes en tramite y fiscalización posterior'},
      { id: uuid(), descripcion: 'Revisión y seguimiento de expedientes y documentos para atención'},
      { id: uuid(), descripcion: 'Toma de entrevistas virtuales'},
      { id: uuid(), descripcion: 'Gestión documental'},
      { id: uuid(), descripcion: 'Toma de entrevista virtual'},
      { id: uuid(), descripcion: 'Inventario de hallazgos'},
      { id: uuid(), descripcion: 'Elaboración de informes técnicos de expedientes PTP'},
      { id: uuid(), descripcion: 'Consolidación de información y actualización de cuadros de Fiscalización Posterior y otros'},
      { id: uuid(), descripcion: 'Gestión documental y coordinación'},
      { id: uuid(), descripcion: 'Consolidación de información y actualización de cuadros de Fiscalización Posterior y otros.'},
      { id: uuid(), descripcion: 'Gestión documental y coodinación.'},
      { id: uuid(), descripcion: 'Elaboración de documentos administrativos.'},
      { id: uuid(), descripcion: 'Revisión de documentos de la SFM.'},
      { id: uuid(), descripcion: 'Coordinaciones administrativas'},
      { id: uuid(), descripcion: 'Revisión de informes en base a diversos medios periodísticos que involucran a ciudadanos extranjeros en actos ilícitos.'},
      { id: uuid(), descripcion: 'Otras actividades.'},
      { id: uuid(), descripcion: 'Revisión y control de calidad de informes técnicos de expedientes de Fiscalización Posterior y en trámite'},
      { id: uuid(), descripcion: 'Revisión y aportes a documentos normativos y del SGC'},
      { id: uuid(), descripcion: 'Coordinaciones administrativas múltiples, y revisión de documentos de la SFM'},
      { id: uuid(), descripcion: 'Gestionar y monitorear los requerimientos operativos y administrativos necesarios para el funcionamiento de la Subdirección Fiscalización Migratoria.'},
      { id: uuid(), descripcion: 'Gestionar y coordinar las unidade móviles de la SFM, los servicios y apoyo a las otras unidades orgánicas de la DGTFM.'},
      { id: uuid(), descripcion: 'Realizar el seguimiento mensual al POI 2021, a fin de cumplir las metas fisicas establecidas para la SFM'},
      { id: uuid(), descripcion: 'Consolidar información de producción y asistencia del personal de la SFM'},
      { id: uuid(), descripcion: 'Gestión Documental (Comunicación de Documentos y atención a través del correo de la SGVF)'},
      { id: uuid(), descripcion: 'Asignación de Documentos a través del SGD'},
      { id: uuid(), descripcion: 'Digitalización y de expedientes'},
      { id: uuid(), descripcion: 'Revisión de informes sobre revisión realizada a diversos medios periodísticos que involucran a ciudadanos extranjeros en actos ilícitos.'},
      { id: uuid(), descripcion: 'Elaboración de informes y hojas de elevación.'},
      { id: uuid(), descripcion: 'Visitas IN SITU en domicilios de administrados'},
      { id: uuid(), descripcion: 'Diligenciamiento y seguimiento de documentos'},
      { id: uuid(), descripcion: 'Consultas en aplicativos SIM INM, SIM RCM y SIM DNV'},
      { id: uuid(), descripcion: 'Operativos de Fiscalización Migratoria'},
      { id: uuid(), descripcion: 'Actividades de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Seguimiento de documentos de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Consolidado de información.'},
      { id: uuid(), descripcion: 'Elaboración de informes administrativos.'},
      { id: uuid(), descripcion: 'Consolidación de información.'},
      { id: uuid(), descripcion: 'Elaboración de documentos adminsitrativos.'},
      { id: uuid(), descripcion: 'Elaboración de documentos.'},
      { id: uuid(), descripcion: 'Consultas en aplicativos SIM INM, SIM RCM y SIM DNV.'},
      { id: uuid(), descripcion: 'Participacion de Operativos de Fiscalizacion Posterior.'},
      { id: uuid(), descripcion: 'Diligenciamiento y seguimiento de documentos.'},
      { id: uuid(), descripcion: 'Participación de operativos de Fiscalización Posterior.'},
      { id: uuid(), descripcion: 'Visitas IN SITU en domicilios de administrados.'},
      { id: uuid(), descripcion: 'Atención de diversos proveídos ( consultas, proyectos de normativas, procedimientos, etc.)'},
      { id: uuid(), descripcion: 'Revisión de documentos normativos para emitir opinión'},
      { id: uuid(), descripcion: 'Verificación de documentación en el SGD.'},
      { id: uuid(), descripcion: 'Verificar y asignar la documentación virtual a través del SGD'},
      { id: uuid(), descripcion: 'Gestión Documental (Comunicación de Documentos correo)'},
      { id: uuid(), descripcion: 'Archivar y ordenar el archivo físico de la documentación que se ha generado en el presente año en los archivadores de la SGVF'},
      { id: uuid(), descripcion: 'Realizar el archivamiento según procedimiento de la documentación de la SGVF para enviar al archivo central (Ordenamiento del Archivo - Año 2017)'},
   ].sort(({descripcion: prev}, { descripcion: current }) => {
      if(prev < current) return -1
      else if(prev > current) return 1
      else 0
   }),
   accionDesarrolladaDb: [
      { id: uuid(), descripcion: 'Informes técnicos de expedientes de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Cartas eleaboradas.'},
      { id: uuid(), descripcion: 'Oficio emitido.'},
      { id: uuid(), descripcion: 'Proveidos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Coordinaciones para emisión de informes.'},
      { id: uuid(), descripcion: 'Carta.'},
      { id: uuid(), descripcion: 'Foleación/union de expediente digital de nacionalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Correcciones de Informes de tramite de nacionbalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Proyecto de informe de nacionalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Toma de entrevistas virtuales.'},
      { id: uuid(), descripcion: 'Recepcion de proveidos y sus respectivas descargas.'},
      { id: uuid(), descripcion: 'Revisión de expediente de tramite por nacionalización por matrimonio.'},
      { id: uuid(), descripcion: 'Carta.'},
      { id: uuid(), descripcion: 'Informe de nacionalización por matrimonio.'},
      { id: uuid(), descripcion: 'Proyecto de informe de nacionalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Entrevistas virtuales.'},
      { id: uuid(), descripcion: 'Recepcion de proveidos y sus respectivas descargas.'},
      { id: uuid(), descripcion: 'Busqueda en sistemas de migraciones y/o afines.'},
      { id: uuid(), descripcion: 'Elaboracion de actas fotograficas.'},
      { id: uuid(), descripcion: 'Digitalizaciones de expediente u otros documentos y foliados respectivamente.'},
      { id: uuid(), descripcion: 'Verificación domiciliaria insitu.'},
      { id: uuid(), descripcion: 'Informes técnicos de expedientes de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Hoja de Elevación elaborada.'},
      { id: uuid(), descripcion: 'Expedientes revisados para le emisión de informes.'},
      { id: uuid(), descripcion: 'Proveidos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Expedientes Unificados y foleados en formato pdf.'},
      { id: uuid(), descripcion: 'Proyecto de informe de fiscalización posterior revisado.'},
      { id: uuid(), descripcion: 'Proyecto de cartas y oficios revisados.'},
      { id: uuid(), descripcion: 'Expedientes revisados para emisión de informes.'},
      { id: uuid(), descripcion: 'Informes técnicos de expedientes de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Proyecto de informe técnico de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Proveidos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Coordinaciones vía telefónica para la emisión de informes.'},
      { id: uuid(), descripcion: 'Capacitación.'},
      { id: uuid(), descripcion: 'Proyectos de Informes técnicos de expedientes de fiscalización posterior elaborados.'},
      { id: uuid(), descripcion: 'Expedientes organizados con diligencias emitidas.'},
      { id: uuid(), descripcion: 'Proyectos de informes de fiscalización posterior revisados.'},
      { id: uuid(), descripcion: 'Proveidos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Proyectos de Cartas y oficios revisados.'},
      { id: uuid(), descripcion: 'Expedientes revisados de fiscalización posterior para emisión de diligencias.'},
      { id: uuid(), descripcion: 'Correos emitidos para seguimiento de diligencias.'},
      { id: uuid(), descripcion: 'Consolidados de reporte de produccion semanal.'},
      { id: uuid(), descripcion: 'Memorandos.'},
      { id: uuid(), descripcion: 'Proyecto de memorando.'},
      { id: uuid(), descripcion: 'Proyecto de hoja de elevacion.'},
      { id: uuid(), descripcion: 'Actualizaciones y/o revision de la base de tramite de nacionalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Busquedas en Sunat y/o aplicativos de migraciones.'},
      { id: uuid(), descripcion: 'Recepción de proveidos y respectivas descargas del contenido delas mismas.'},
      { id: uuid(), descripcion: 'Verificacion de hallazgos de fiscalizacion posterior.'},
      { id: uuid(), descripcion: 'Reunion de la SFM(coordinadores).'},
      { id: uuid(), descripcion: 'Coordinaciones con equipo de trabajo respecto a la base de hospedajes, aclaraciones de consultas entre otros y /o de tramite de nacionalizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Actualizaciones de la base de datos de fiscalización posterior 2021.'},
      { id: uuid(), descripcion: 'Proveídos recepcionado y atendidos.'},
      { id: uuid(), descripcion: 'Actualizaciones de diligencias de fiscalización posterior.'},
      { id: uuid(), descripcion: 'Consolidado semanal de Reporte Semanal de Actividades.'},
      { id: uuid(), descripcion: 'Llamadas de coordinación.'},
      { id: uuid(), descripcion: 'Correos remitidos para coordinación de actividades de fiscalización posterior y respuesta de solicitud de información.'},
      { id: uuid(), descripcion: 'Expedientes diligitales revisados que contengan diligencias.'},
      { id: uuid(), descripcion: 'Elaboración de cuadro resumen de avance carga por abogado.'},
      { id: uuid(), descripcion: 'Proveido emitido para asignación de expedientes.'},
      { id: uuid(), descripcion: 'Capacitaciones.'},
      { id: uuid(), descripcion: 'Revisiones de Directiva para emitir comentario.'},
      { id: uuid(), descripcion: 'Informes de fiscalización posterior revisados para verificar hallazgos.'},
      { id: uuid(), descripcion: 'Búsqueda de información de años 2019 y 2020 para informe de gestión.'},
      { id: uuid(), descripcion: 'Informes sobre la gestión de la SFM.'},
      { id: uuid(), descripcion: 'Hojas de Elevación sobre la gestión de la SFM.'},
      { id: uuid(), descripcion: 'Órdenes de operativos de verificación y fiscalización migratoria.'},
      { id: uuid(), descripcion: 'Revisiones de informes sobre ciudadanos extranjeros en actos ilícitos reportados en medios periodísticos.'},
      { id: uuid(), descripcion: 'Revisión de documentos administrativos relacionados a antecedentes internacionales de ciudadanos extranjeros.'},
      { id: uuid(), descripcion: 'Opiniones sobre documentos normativos (Procedimiento e Instructivo sobre Emisión de Carné de Extranjería por cambio de calidad migratoria).'},
      { id: uuid(), descripcion: 'Requerimiento de pedido sobre una reunión que solictó una empresa de tecnología de control de fronteras.'},
      { id: uuid(), descripcion: 'Revisión de la propuesta de cadena de valor de los Procesos Misionales.'},
      { id: uuid(), descripcion: 'Coordinaciones para la programación de entrevistas para administrados.'},
      { id: uuid(), descripcion: 'Coordinación para elaboración de cronograma de operativos en el AIJCH en el mes de mayo.'},
      { id: uuid(), descripcion: 'Coordinaciones, supervisiones y control de los operativos de verificación y fiscalización migratoria.'},
      { id: uuid(), descripcion: 'Coordinaciones con la Subdirectora de Fiscalización Migratoria.'},
      { id: uuid(), descripcion: 'Coordinación para la elaboración de actas de desplazamiento de bienes patrimoniales para el desarrollo de operativos.'},
      { id: uuid(), descripcion: 'Coordinaciones con fiscalizadores en atención a las actividades de verificación y fiscalización.'},
      { id: uuid(), descripcion: 'Hojas de Elevación.'},
      { id: uuid(), descripcion: 'Proveídos.'},
      { id: uuid(), descripcion: 'Revisiones y control de calidad de informes tecnicos y documentos colgados por el personal en el SGD.'},
      { id: uuid(), descripcion: 'Coordinaciones telefónicas para el levantamiento de observaciones.'},
      { id: uuid(), descripcion: 'Correos electrónicos emitidos a servidores de la SFM.'},
      { id: uuid(), descripcion: 'Hallazgos caso universidad Unión.'},
      { id: uuid(), descripcion: 'Correos enviados.'},
      { id: uuid(), descripcion: 'Hojas de Elevación elaboradas.'},
      { id: uuid(), descripcion: 'Recepción de Proveídos.'},
      { id: uuid(), descripcion: 'Informe.'},
      { id: uuid(), descripcion: 'Capacitación.'},
      { id: uuid(), descripcion: 'Reporte te de Personal por temas de vacuna COVID-19.'},
      { id: uuid(), descripcion: 'Programación de actividades para la primera semana de mayo.'},
      { id: uuid(), descripcion: 'Coordinaciones con los encargados para el levantamiento del inventario anual de bienes patrimoniales.'},
      { id: uuid(), descripcion: 'Coordinación con OTIC para los accesos y bajas de personal nuevo y saliente.'},
      { id: uuid(), descripcion: 'Consolidado de producción semanal del personal.'},
      { id: uuid(), descripcion: 'Coordinaciones con RH por errores en certificados de personal, coordinaciones con Dirección por el tema de capacitación del RIM, además de coordinar los apoyos de movilidades a otras unidades orgánica y las comisiones de servicio diarias para el traslado del personal a diferentes distritos de Lima Metropolitana.'},
      { id: uuid(), descripcion: 'Descargas y Renombramiento de documentación.'},
      { id: uuid(), descripcion: 'Envío de documentación a entidades públicas y/o administrados.'},
      { id: uuid(), descripcion: 'Documentos archivados digitalmente.'},
      { id: uuid(), descripcion: 'Respuesta a solicitud(es) de información interna y externa.'},
      { id: uuid(), descripcion: 'Coordinaciones para actividades a realizar (diligenciamiento de documentos).'},
      { id: uuid(), descripcion: 'Proveidos elaborados de asignación documental.'},
      { id: uuid(), descripcion: 'Atención de llamadas telefónicas.'},
      { id: uuid(), descripcion: 'Digitalizaciones de documentos.'},
      { id: uuid(), descripcion: 'Revisión en diferentes medios periodísticos, noticias que impliquen a extranjeros en delitos.'},
      { id: uuid(), descripcion: 'Informes sobre ciudadanos extranjeros en actos ilícitos reportados en medios periodísticos.'},
      { id: uuid(), descripcion: 'Hoja de elevación.'},
      { id: uuid(), descripcion: 'Incidencia en la opción de busqueda de registro en el Aplicativo SIM-NAC reportado a mesa de servicio atraves del Correo Electrónico Institucional.'},
      { id: uuid(), descripcion: 'Solicitud de Actas de Desplazamiento de Bienes para desarrollo de Activdad Operativa (Operativos de Verificación y Fiscalización en el AIJCH).'},
      { id: uuid(), descripcion: 'Apoyo en la elaboración del Cronograma y formación de grupos de los Operativos de Verificación y Fiscalización Migratoria correspondiente al mes de Mayo 2021 en el Aeropuerto Internacional Jorge Chávez.'},
      { id: uuid(), descripcion: 'Cartas elaboradas.'},
      { id: uuid(), descripcion: 'Oficio elaborado.'},
      { id: uuid(), descripcion: 'Proveídos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Expedientes de pasaporte electronico revisado para elaboración de informes.'},
      { id: uuid(), descripcion: 'Proyectos de informe de pasaporte electrónico.'},
      { id: uuid(), descripcion: 'Administrados consultados en plataforma INTERPOL.'},
      { id: uuid(), descripcion: 'Notificaciones de documentos IN-SITU.'},
      { id: uuid(), descripcion: 'Expedientes revisados para emisión de reiterativos de información.'},
      { id: uuid(), descripcion: 'Operativo presencial en Aeropuerto Jorge Chávez.'},
      { id: uuid(), descripcion: 'Documentos con sustento fotográfico elaborados.'},
      { id: uuid(), descripcion: 'Seguimiento de respuesta de 15 solicitudes de información.'},
      { id: uuid(), descripcion: 'Actualización de base de expedientes de nacionalización.'},
      { id: uuid(), descripcion: 'Actualización de cuadro de prorroga de residencia y Nacionalización.'},
      { id: uuid(), descripcion: 'Seguimiento de respuestas trámites de prórroga de residencia y nacionalización.'},
      { id: uuid(), descripcion: 'Validaciones de fichas de interpol.'},
      { id: uuid(), descripcion: 'Diligencias de la SFM.'},
      { id: uuid(), descripcion: 'Apoyo en la actualización de cuadros sobre programación de entrevistas virtuales de la SFM.'},
      { id: uuid(), descripcion: 'Apoyo en la elaboración del informe sobre los compromisos de las partes del convenio interinstitucional entre el Ministerio de Transporte y Migraciones.'},
      { id: uuid(), descripcion: 'Apoyo en operativo de verificación y fiscalización migratoria en el Aeropuerto Internacional Jorge Chávez.'},
      { id: uuid(), descripcion: 'Apoyo en la elaboración del informe sobre la remisión del protocolo e instructivo de verificación y fiscalización migratoria en los Puestos de Verificación Migratoria a la DGTFM para su aprobación.'},
      { id: uuid(), descripcion: 'Apoyo en la elaboración de la Orden de operativo de verificación y fiscalización migratoria en el Aeropuerto Internacional Jorge Chávez del 30/04/2021.'},
      { id: uuid(), descripcion: 'Apoyo en la elaboración del Informe sobre el Convenio entre el Poder Judicial y MIGRACIONES.'},
      { id: uuid(), descripcion: 'Reporte integral semanal.'},
      { id: uuid(), descripcion: 'Actualización de cuadro integral de operativos y documentos anexos.'},
      { id: uuid(), descripcion: 'Actualización de cuadro de intervenidos en operativos 2021.'},
      { id: uuid(), descripcion: 'Actualizaciones de carpetas de operativos.'},
      { id: uuid(), descripcion: 'Proyecto de informe de pasaporte electronico- fiscalización posterior.'},
      { id: uuid(), descripcion: 'Oficios de fiscalizacion posterior.'},
      { id: uuid(), descripcion: 'Recepcion de proveidos y sus descarga respectivas.'},
      { id: uuid(), descripcion: 'Revisiones de expedientes de fiscalizacion posterior.'},
      { id: uuid(), descripcion: 'Actualizacion de base de excel de fiscalizacion posterior - naciobalización por matrimonio y/o prorroga de residencia.'},
      { id: uuid(), descripcion: 'Verificacionesen página de SUNAT y/o otros aplicativos afines respecto al estado de las deligencias de los expedientes de prórroga de residencia y/o nacionaizacion por matrimonio.'},
      { id: uuid(), descripcion: 'Participacion en operativo de fiscalizacion en el aeropuerto.'},
      { id: uuid(), descripcion: 'Cartas de establecimientos de hospedajes.'},
      { id: uuid(), descripcion: 'Actualizaciones de registros en la base de establecimiento de hospedajes 2021.'},
      { id: uuid(), descripcion: 'Proyectos de cartas de establecimientos de hospedajes.'},
      { id: uuid(), descripcion: 'Búsquedas y/o validaciones en sistemas SIM-IN, SIM RCM, DNV y/o aplicativos complementarios.'},
      { id: uuid(), descripcion: 'Validaciones de cargos de notificación de tablecimientos de hospedajes.'},
      { id: uuid(), descripcion: 'Proyectos de informes de fiscalización.'},
      { id: uuid(), descripcion: 'Proveidos recepcionados y anexados a expedientes digitales.'},
      { id: uuid(), descripcion: 'Actualización de base de expedientes.'},
      { id: uuid(), descripcion: 'Participacion en operativo de fiscalizacion en el aeropuerto.'},
      { id: uuid(), descripcion: 'Operativo presencial en Aeropuerto Jorge Chávez.'},
      { id: uuid(), descripcion: 'Ciudadanos intervenidos.'},
      { id: uuid(), descripcion: 'Notificaciones de documentos IN-SITU.'},
      { id: uuid(), descripcion: 'Administrados consultados en plataforma INTERPOL.'},
      { id: uuid(), descripcion: 'Actualización de diligencias.'},
      { id: uuid(), descripcion: 'Administrados consultados en SIM INM para completar datos de excel de Fiscalización Posterior 2021.'},
      { id: uuid(), descripcion: 'Notificaciones de documentos IN-SITU.'},
      { id: uuid(), descripcion: 'Operativo presencial en Aeropuerto Jorge Chávez.'},
      { id: uuid(), descripcion: 'Documentos con sustento fotográfico elaborados.'},
      { id: uuid(), descripcion: 'Hojas de elevación.'},
      { id: uuid(), descripcion: 'Informe.'},
      { id: uuid(), descripcion: 'Recepción de Proveídos.'},
      { id: uuid(), descripcion: 'Capacitación.'},
      { id: uuid(), descripcion: 'Reunión de Trabajo Validación Visa Humanitaria.'},
      { id: uuid(), descripcion: 'Revisiones de base legal para la emisión de opiones solicitadas.'},
      { id: uuid(), descripcion: 'Seguimiento a Oficio 738.'},
      { id: uuid(), descripcion: 'Descargas de expedientes digitales.'},
      { id: uuid(), descripcion: 'Seguimiento de expedientes vía telefónica y vía correo electrónico.'},
      { id: uuid(), descripcion: 'Proveidos emitidos.'},
      { id: uuid(), descripcion: 'Proveidos recibidos.'},
      { id: uuid(), descripcion: 'Seguimientos a los documentos en espera de respuesta por parte de las entidades publicas como RENAJU, INTERPOL,INPE ENTRE OTROS.'},
      { id: uuid(), descripcion: 'Envíos de correos electrónicos para solicitar respuesta del documento enviado.'},
      { id: uuid(), descripcion: 'Llamadas telefónicas las diversas entidades públicas para consulta de respuestas de documentación enviada por Migraciones.'},
      { id: uuid(), descripcion: 'Coordinaciones por correo y llamadas telefonicas con los servidores de trabajo.'},
      { id: uuid(), descripcion: 'Licencia con goce.'},
   ].sort(({descripcion: prev}, { descripcion: current }) => {
      if(prev < current) return -1
      else if(prev > current) return 1
      else 0
   })
}

